In [22]:
import numpy as np

A = np.array([[0, 1],
              [2, 3],
              [4, 5]])
B = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])
result = np.dot(A, B)

print("行列の積の計算")
print(result)

max_value = np.max(result)
print("計算された行列の要素の最大値:", max_value)

行列の積の計算
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
計算された行列の要素の最大値: 47
